spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    properties:
      hibernate:
         show_sql: true
         format_sql: true
         dialect: org.hibernate.dialect.OracleDialect
   # hibernate:
   #   ddl-auto: update